default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POLL_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POLL_DB_1_PORT_5432_TCP_PORT'] %>
  pool: 5

production:
  <<: *default
  database: poll_prod

development:
  <<: *default
  database: poll_dev

test:
  <<: *default
  database: poll_test

